{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pvc-viewer
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  tls:
  {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts: {{ toYaml .hosts | nindent 8 }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pvc-viewer-backend
                port:
                  number: 80
  {{- end }}
{{- end }}



