apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pvc-viewer-backend
spec:
  podSelector:
    matchLabels:
      app: pvc-viewer-backend
  policyTypes: [Ingress, Egress]
  ingress:
    - {}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8090



