name: Helm CI

on:
  push:
    tags: [ 'v*' ]

jobs:
  helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Helm lint
        run: |
          helm lint helm/pvc-viewer
      - name: Trivy scan (Helm chart IAC)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          scan-ref: 'helm/pvc-viewer'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
      - name: Package chart
        run: |
          mkdir -p dist
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION=${GITHUB_REF_NAME#v}
          else
            VERSION=0.0.0-${GITHUB_SHA::7}
          fi
          helm package helm/pvc-viewer --version ${VERSION} --app-version ${VERSION} -d dist
      - name: Login to GHCR (OCI)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push chart to GHCR (OCI)
        run: |
          CHART_TGZ=$(ls dist/*.tgz | head -n1)
          helm push $CHART_TGZ oci://ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/charts
