name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: '{}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Package Helm chart
        run: |
          helm dependency build helm/pvc-viewer || true
          helm package helm/pvc-viewer --version ${GITHUB_REF_NAME#v} --app-version ${GITHUB_REF_NAME#v} -d dist

      - name: Upload chart artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tgz

      - name: Login to GHCR (OCI)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm chart to GHCR (OCI)
        run: |
          CHART_TGZ=$(ls dist/*.tgz | head -n1)
          helm push $CHART_TGZ oci://ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/charts
